// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: garage.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GarageService_RotateCarrier_FullMethodName       = "/garage.GarageService/RotateCarrier"
	GarageService_GetCarrierStatus_FullMethodName    = "/garage.GarageService/GetCarrierStatus"
	GarageService_GetWeightStatus_FullMethodName     = "/garage.GarageService/GetWeightStatus"
	GarageService_EmergencyStop_FullMethodName       = "/garage.GarageService/EmergencyStop"
	GarageService_StreamCarrierStatus_FullMethodName = "/garage.GarageService/StreamCarrierStatus"
)

// GarageServiceClient is the client API for GarageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GarageServiceClient interface {
	RotateCarrier(ctx context.Context, in *RotateRequest, opts ...grpc.CallOption) (*RotateResponse, error)
	GetCarrierStatus(ctx context.Context, in *GetCarrierStatusRequest, opts ...grpc.CallOption) (*GetCarrierStatusResponse, error)
	GetWeightStatus(ctx context.Context, in *GetWeightStatusRequest, opts ...grpc.CallOption) (*GetWeightStatusResponse, error)
	EmergencyStop(ctx context.Context, in *EmergencyStopRequest, opts ...grpc.CallOption) (*EmergencyStopResponse, error)
	StreamCarrierStatus(ctx context.Context, in *StreamCarrierStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CarrierStatusUpdate], error)
}

type garageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGarageServiceClient(cc grpc.ClientConnInterface) GarageServiceClient {
	return &garageServiceClient{cc}
}

func (c *garageServiceClient) RotateCarrier(ctx context.Context, in *RotateRequest, opts ...grpc.CallOption) (*RotateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateResponse)
	err := c.cc.Invoke(ctx, GarageService_RotateCarrier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *garageServiceClient) GetCarrierStatus(ctx context.Context, in *GetCarrierStatusRequest, opts ...grpc.CallOption) (*GetCarrierStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCarrierStatusResponse)
	err := c.cc.Invoke(ctx, GarageService_GetCarrierStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *garageServiceClient) GetWeightStatus(ctx context.Context, in *GetWeightStatusRequest, opts ...grpc.CallOption) (*GetWeightStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeightStatusResponse)
	err := c.cc.Invoke(ctx, GarageService_GetWeightStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *garageServiceClient) EmergencyStop(ctx context.Context, in *EmergencyStopRequest, opts ...grpc.CallOption) (*EmergencyStopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmergencyStopResponse)
	err := c.cc.Invoke(ctx, GarageService_EmergencyStop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *garageServiceClient) StreamCarrierStatus(ctx context.Context, in *StreamCarrierStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CarrierStatusUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GarageService_ServiceDesc.Streams[0], GarageService_StreamCarrierStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamCarrierStatusRequest, CarrierStatusUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GarageService_StreamCarrierStatusClient = grpc.ServerStreamingClient[CarrierStatusUpdate]

// GarageServiceServer is the server API for GarageService service.
// All implementations must embed UnimplementedGarageServiceServer
// for forward compatibility.
type GarageServiceServer interface {
	RotateCarrier(context.Context, *RotateRequest) (*RotateResponse, error)
	GetCarrierStatus(context.Context, *GetCarrierStatusRequest) (*GetCarrierStatusResponse, error)
	GetWeightStatus(context.Context, *GetWeightStatusRequest) (*GetWeightStatusResponse, error)
	EmergencyStop(context.Context, *EmergencyStopRequest) (*EmergencyStopResponse, error)
	StreamCarrierStatus(*StreamCarrierStatusRequest, grpc.ServerStreamingServer[CarrierStatusUpdate]) error
	mustEmbedUnimplementedGarageServiceServer()
}

// UnimplementedGarageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGarageServiceServer struct{}

func (UnimplementedGarageServiceServer) RotateCarrier(context.Context, *RotateRequest) (*RotateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateCarrier not implemented")
}
func (UnimplementedGarageServiceServer) GetCarrierStatus(context.Context, *GetCarrierStatusRequest) (*GetCarrierStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCarrierStatus not implemented")
}
func (UnimplementedGarageServiceServer) GetWeightStatus(context.Context, *GetWeightStatusRequest) (*GetWeightStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeightStatus not implemented")
}
func (UnimplementedGarageServiceServer) EmergencyStop(context.Context, *EmergencyStopRequest) (*EmergencyStopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmergencyStop not implemented")
}
func (UnimplementedGarageServiceServer) StreamCarrierStatus(*StreamCarrierStatusRequest, grpc.ServerStreamingServer[CarrierStatusUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamCarrierStatus not implemented")
}
func (UnimplementedGarageServiceServer) mustEmbedUnimplementedGarageServiceServer() {}
func (UnimplementedGarageServiceServer) testEmbeddedByValue()                       {}

// UnsafeGarageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GarageServiceServer will
// result in compilation errors.
type UnsafeGarageServiceServer interface {
	mustEmbedUnimplementedGarageServiceServer()
}

func RegisterGarageServiceServer(s grpc.ServiceRegistrar, srv GarageServiceServer) {
	// If the following call panics, it indicates UnimplementedGarageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GarageService_ServiceDesc, srv)
}

func _GarageService_RotateCarrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GarageServiceServer).RotateCarrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GarageService_RotateCarrier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GarageServiceServer).RotateCarrier(ctx, req.(*RotateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GarageService_GetCarrierStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCarrierStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GarageServiceServer).GetCarrierStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GarageService_GetCarrierStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GarageServiceServer).GetCarrierStatus(ctx, req.(*GetCarrierStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GarageService_GetWeightStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeightStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GarageServiceServer).GetWeightStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GarageService_GetWeightStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GarageServiceServer).GetWeightStatus(ctx, req.(*GetWeightStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GarageService_EmergencyStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmergencyStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GarageServiceServer).EmergencyStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GarageService_EmergencyStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GarageServiceServer).EmergencyStop(ctx, req.(*EmergencyStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GarageService_StreamCarrierStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamCarrierStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GarageServiceServer).StreamCarrierStatus(m, &grpc.GenericServerStream[StreamCarrierStatusRequest, CarrierStatusUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GarageService_StreamCarrierStatusServer = grpc.ServerStreamingServer[CarrierStatusUpdate]

// GarageService_ServiceDesc is the grpc.ServiceDesc for GarageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GarageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "garage.GarageService",
	HandlerType: (*GarageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RotateCarrier",
			Handler:    _GarageService_RotateCarrier_Handler,
		},
		{
			MethodName: "GetCarrierStatus",
			Handler:    _GarageService_GetCarrierStatus_Handler,
		},
		{
			MethodName: "GetWeightStatus",
			Handler:    _GarageService_GetWeightStatus_Handler,
		},
		{
			MethodName: "EmergencyStop",
			Handler:    _GarageService_EmergencyStop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCarrierStatus",
			Handler:       _GarageService_StreamCarrierStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "garage.proto",
}
