// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: garage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RotateDirection int32

const (
	RotateDirection_CLOCKWISE         RotateDirection = 0
	RotateDirection_COUNTER_CLOCKWISE RotateDirection = 1
)

// Enum value maps for RotateDirection.
var (
	RotateDirection_name = map[int32]string{
		0: "CLOCKWISE",
		1: "COUNTER_CLOCKWISE",
	}
	RotateDirection_value = map[string]int32{
		"CLOCKWISE":         0,
		"COUNTER_CLOCKWISE": 1,
	}
)

func (x RotateDirection) Enum() *RotateDirection {
	p := new(RotateDirection)
	*p = x
	return p
}

func (x RotateDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RotateDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_garage_proto_enumTypes[0].Descriptor()
}

func (RotateDirection) Type() protoreflect.EnumType {
	return &file_garage_proto_enumTypes[0]
}

func (x RotateDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RotateDirection.Descriptor instead.
func (RotateDirection) EnumDescriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{0}
}

type CarrierStatus int32

const (
	CarrierStatus_IDLE              CarrierStatus = 0
	CarrierStatus_ROTATING          CarrierStatus = 1
	CarrierStatus_EMERGENCY_STOPPED CarrierStatus = 2
	CarrierStatus_WEIGHT_OVERLOAD   CarrierStatus = 3
	CarrierStatus_OBSTRUCTED        CarrierStatus = 4
)

// Enum value maps for CarrierStatus.
var (
	CarrierStatus_name = map[int32]string{
		0: "IDLE",
		1: "ROTATING",
		2: "EMERGENCY_STOPPED",
		3: "WEIGHT_OVERLOAD",
		4: "OBSTRUCTED",
	}
	CarrierStatus_value = map[string]int32{
		"IDLE":              0,
		"ROTATING":          1,
		"EMERGENCY_STOPPED": 2,
		"WEIGHT_OVERLOAD":   3,
		"OBSTRUCTED":        4,
	}
)

func (x CarrierStatus) Enum() *CarrierStatus {
	p := new(CarrierStatus)
	*p = x
	return p
}

func (x CarrierStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CarrierStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_garage_proto_enumTypes[1].Descriptor()
}

func (CarrierStatus) Type() protoreflect.EnumType {
	return &file_garage_proto_enumTypes[1]
}

func (x CarrierStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CarrierStatus.Descriptor instead.
func (CarrierStatus) EnumDescriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{1}
}

type RotateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarrierId     int32                  `protobuf:"varint,1,opt,name=carrier_id,json=carrierId,proto3" json:"carrier_id,omitempty"`
	Direction     RotateDirection        `protobuf:"varint,2,opt,name=direction,proto3,enum=garage.RotateDirection" json:"direction,omitempty"`
	Steps         int32                  `protobuf:"varint,3,opt,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateRequest) Reset() {
	*x = RotateRequest{}
	mi := &file_garage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateRequest) ProtoMessage() {}

func (x *RotateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateRequest.ProtoReflect.Descriptor instead.
func (*RotateRequest) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{0}
}

func (x *RotateRequest) GetCarrierId() int32 {
	if x != nil {
		return x.CarrierId
	}
	return 0
}

func (x *RotateRequest) GetDirection() RotateDirection {
	if x != nil {
		return x.Direction
	}
	return RotateDirection_CLOCKWISE
}

func (x *RotateRequest) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

type RotateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EstimatedTimeMs int32                  `protobuf:"varint,3,opt,name=estimated_time_ms,json=estimatedTimeMs,proto3" json:"estimated_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RotateResponse) Reset() {
	*x = RotateResponse{}
	mi := &file_garage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateResponse) ProtoMessage() {}

func (x *RotateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateResponse.ProtoReflect.Descriptor instead.
func (*RotateResponse) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{1}
}

func (x *RotateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RotateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RotateResponse) GetEstimatedTimeMs() int32 {
	if x != nil {
		return x.EstimatedTimeMs
	}
	return 0
}

type GetCarrierStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarrierId     int32                  `protobuf:"varint,1,opt,name=carrier_id,json=carrierId,proto3" json:"carrier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCarrierStatusRequest) Reset() {
	*x = GetCarrierStatusRequest{}
	mi := &file_garage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCarrierStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCarrierStatusRequest) ProtoMessage() {}

func (x *GetCarrierStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCarrierStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCarrierStatusRequest) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{2}
}

func (x *GetCarrierStatusRequest) GetCarrierId() int32 {
	if x != nil {
		return x.CarrierId
	}
	return 0
}

type GetCarrierStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             CarrierStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=garage.CarrierStatus" json:"status,omitempty"`
	CurrentFloor       int32                  `protobuf:"varint,2,opt,name=current_floor,json=currentFloor,proto3" json:"current_floor,omitempty"`
	GroundCarrierIndex int32                  `protobuf:"varint,3,opt,name=ground_carrier_index,json=groundCarrierIndex,proto3" json:"ground_carrier_index,omitempty"`
	CurrentAngle       float32                `protobuf:"fixed32,4,opt,name=current_angle,json=currentAngle,proto3" json:"current_angle,omitempty"`
	CarrierAngles      []float32              `protobuf:"fixed32,5,rep,packed,name=carrier_angles,json=carrierAngles,proto3" json:"carrier_angles,omitempty"`
	LicensePlates      []string               `protobuf:"bytes,6,rep,name=license_plates,json=licensePlates,proto3" json:"license_plates,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetCarrierStatusResponse) Reset() {
	*x = GetCarrierStatusResponse{}
	mi := &file_garage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCarrierStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCarrierStatusResponse) ProtoMessage() {}

func (x *GetCarrierStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCarrierStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCarrierStatusResponse) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{3}
}

func (x *GetCarrierStatusResponse) GetStatus() CarrierStatus {
	if x != nil {
		return x.Status
	}
	return CarrierStatus_IDLE
}

func (x *GetCarrierStatusResponse) GetCurrentFloor() int32 {
	if x != nil {
		return x.CurrentFloor
	}
	return 0
}

func (x *GetCarrierStatusResponse) GetGroundCarrierIndex() int32 {
	if x != nil {
		return x.GroundCarrierIndex
	}
	return 0
}

func (x *GetCarrierStatusResponse) GetCurrentAngle() float32 {
	if x != nil {
		return x.CurrentAngle
	}
	return 0
}

func (x *GetCarrierStatusResponse) GetCarrierAngles() []float32 {
	if x != nil {
		return x.CarrierAngles
	}
	return nil
}

func (x *GetCarrierStatusResponse) GetLicensePlates() []string {
	if x != nil {
		return x.LicensePlates
	}
	return nil
}

type GetWeightStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarrierIndex  int32                  `protobuf:"varint,1,opt,name=carrier_index,json=carrierIndex,proto3" json:"carrier_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeightStatusRequest) Reset() {
	*x = GetWeightStatusRequest{}
	mi := &file_garage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeightStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeightStatusRequest) ProtoMessage() {}

func (x *GetWeightStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeightStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWeightStatusRequest) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{4}
}

func (x *GetWeightStatusRequest) GetCarrierIndex() int32 {
	if x != nil {
		return x.CarrierIndex
	}
	return 0
}

type GetWeightStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeightKg      float32                `protobuf:"fixed32,1,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	IsOverload    bool                   `protobuf:"varint,2,opt,name=is_overload,json=isOverload,proto3" json:"is_overload,omitempty"`
	MaxWeightKg   float32                `protobuf:"fixed32,3,opt,name=max_weight_kg,json=maxWeightKg,proto3" json:"max_weight_kg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeightStatusResponse) Reset() {
	*x = GetWeightStatusResponse{}
	mi := &file_garage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeightStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeightStatusResponse) ProtoMessage() {}

func (x *GetWeightStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeightStatusResponse.ProtoReflect.Descriptor instead.
func (*GetWeightStatusResponse) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{5}
}

func (x *GetWeightStatusResponse) GetWeightKg() float32 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *GetWeightStatusResponse) GetIsOverload() bool {
	if x != nil {
		return x.IsOverload
	}
	return false
}

func (x *GetWeightStatusResponse) GetMaxWeightKg() float32 {
	if x != nil {
		return x.MaxWeightKg
	}
	return 0
}

type ReadGroundScaleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadGroundScaleRequest) Reset() {
	*x = ReadGroundScaleRequest{}
	mi := &file_garage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadGroundScaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadGroundScaleRequest) ProtoMessage() {}

func (x *ReadGroundScaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadGroundScaleRequest.ProtoReflect.Descriptor instead.
func (*ReadGroundScaleRequest) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{6}
}

type ReadGroundScaleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeightKg      float32                `protobuf:"fixed32,1,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	IsOverload    bool                   `protobuf:"varint,2,opt,name=is_overload,json=isOverload,proto3" json:"is_overload,omitempty"`
	MaxWeightKg   float32                `protobuf:"fixed32,3,opt,name=max_weight_kg,json=maxWeightKg,proto3" json:"max_weight_kg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadGroundScaleResponse) Reset() {
	*x = ReadGroundScaleResponse{}
	mi := &file_garage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadGroundScaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadGroundScaleResponse) ProtoMessage() {}

func (x *ReadGroundScaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadGroundScaleResponse.ProtoReflect.Descriptor instead.
func (*ReadGroundScaleResponse) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{7}
}

func (x *ReadGroundScaleResponse) GetWeightKg() float32 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *ReadGroundScaleResponse) GetIsOverload() bool {
	if x != nil {
		return x.IsOverload
	}
	return false
}

func (x *ReadGroundScaleResponse) GetMaxWeightKg() float32 {
	if x != nil {
		return x.MaxWeightKg
	}
	return 0
}

type SetGroundScaleOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeightKg      float32                `protobuf:"fixed32,1,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroundScaleOverrideRequest) Reset() {
	*x = SetGroundScaleOverrideRequest{}
	mi := &file_garage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroundScaleOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroundScaleOverrideRequest) ProtoMessage() {}

func (x *SetGroundScaleOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroundScaleOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetGroundScaleOverrideRequest) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{8}
}

func (x *SetGroundScaleOverrideRequest) GetWeightKg() float32 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

type SetGroundScaleOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroundScaleOverrideResponse) Reset() {
	*x = SetGroundScaleOverrideResponse{}
	mi := &file_garage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroundScaleOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroundScaleOverrideResponse) ProtoMessage() {}

func (x *SetGroundScaleOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroundScaleOverrideResponse.ProtoReflect.Descriptor instead.
func (*SetGroundScaleOverrideResponse) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{9}
}

func (x *SetGroundScaleOverrideResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetGroundScaleOverrideResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EmergencyStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergencyStopRequest) Reset() {
	*x = EmergencyStopRequest{}
	mi := &file_garage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergencyStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergencyStopRequest) ProtoMessage() {}

func (x *EmergencyStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergencyStopRequest.ProtoReflect.Descriptor instead.
func (*EmergencyStopRequest) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{10}
}

func (x *EmergencyStopRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EmergencyStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergencyStopResponse) Reset() {
	*x = EmergencyStopResponse{}
	mi := &file_garage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergencyStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergencyStopResponse) ProtoMessage() {}

func (x *EmergencyStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergencyStopResponse.ProtoReflect.Descriptor instead.
func (*EmergencyStopResponse) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{11}
}

func (x *EmergencyStopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmergencyStopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamCarrierStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarrierId     int32                  `protobuf:"varint,1,opt,name=carrier_id,json=carrierId,proto3" json:"carrier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCarrierStatusRequest) Reset() {
	*x = StreamCarrierStatusRequest{}
	mi := &file_garage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCarrierStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCarrierStatusRequest) ProtoMessage() {}

func (x *StreamCarrierStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCarrierStatusRequest.ProtoReflect.Descriptor instead.
func (*StreamCarrierStatusRequest) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{12}
}

func (x *StreamCarrierStatusRequest) GetCarrierId() int32 {
	if x != nil {
		return x.CarrierId
	}
	return 0
}

type CarrierStatusUpdate struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             CarrierStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=garage.CarrierStatus" json:"status,omitempty"`
	GroundCarrierIndex int32                  `protobuf:"varint,2,opt,name=ground_carrier_index,json=groundCarrierIndex,proto3" json:"ground_carrier_index,omitempty"`
	CurrentAngle       float32                `protobuf:"fixed32,3,opt,name=current_angle,json=currentAngle,proto3" json:"current_angle,omitempty"`
	Timestamp          int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TargetCarrierIndex *int32                 `protobuf:"varint,5,opt,name=target_carrier_index,json=targetCarrierIndex,proto3,oneof" json:"target_carrier_index,omitempty"`
	Progress           *float32               `protobuf:"fixed32,6,opt,name=progress,proto3,oneof" json:"progress,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CarrierStatusUpdate) Reset() {
	*x = CarrierStatusUpdate{}
	mi := &file_garage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarrierStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarrierStatusUpdate) ProtoMessage() {}

func (x *CarrierStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_garage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarrierStatusUpdate.ProtoReflect.Descriptor instead.
func (*CarrierStatusUpdate) Descriptor() ([]byte, []int) {
	return file_garage_proto_rawDescGZIP(), []int{13}
}

func (x *CarrierStatusUpdate) GetStatus() CarrierStatus {
	if x != nil {
		return x.Status
	}
	return CarrierStatus_IDLE
}

func (x *CarrierStatusUpdate) GetGroundCarrierIndex() int32 {
	if x != nil {
		return x.GroundCarrierIndex
	}
	return 0
}

func (x *CarrierStatusUpdate) GetCurrentAngle() float32 {
	if x != nil {
		return x.CurrentAngle
	}
	return 0
}

func (x *CarrierStatusUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CarrierStatusUpdate) GetTargetCarrierIndex() int32 {
	if x != nil && x.TargetCarrierIndex != nil {
		return *x.TargetCarrierIndex
	}
	return 0
}

func (x *CarrierStatusUpdate) GetProgress() float32 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

var File_garage_proto protoreflect.FileDescriptor

const file_garage_proto_rawDesc = "" +
	"\n" +
	"\fgarage.proto\x12\x06garage\"{\n" +
	"\rRotateRequest\x12\x1d\n" +
	"\n" +
	"carrier_id\x18\x01 \x01(\x05R\tcarrierId\x125\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x17.garage.RotateDirectionR\tdirection\x12\x14\n" +
	"\x05steps\x18\x03 \x01(\x05R\x05steps\"p\n" +
	"\x0eRotateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x11estimated_time_ms\x18\x03 \x01(\x05R\x0festimatedTimeMs\"8\n" +
	"\x17GetCarrierStatusRequest\x12\x1d\n" +
	"\n" +
	"carrier_id\x18\x01 \x01(\x05R\tcarrierId\"\x93\x02\n" +
	"\x18GetCarrierStatusResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.garage.CarrierStatusR\x06status\x12#\n" +
	"\rcurrent_floor\x18\x02 \x01(\x05R\fcurrentFloor\x120\n" +
	"\x14ground_carrier_index\x18\x03 \x01(\x05R\x12groundCarrierIndex\x12#\n" +
	"\rcurrent_angle\x18\x04 \x01(\x02R\fcurrentAngle\x12%\n" +
	"\x0ecarrier_angles\x18\x05 \x03(\x02R\rcarrierAngles\x12%\n" +
	"\x0elicense_plates\x18\x06 \x03(\tR\rlicensePlates\"=\n" +
	"\x16GetWeightStatusRequest\x12#\n" +
	"\rcarrier_index\x18\x01 \x01(\x05R\fcarrierIndex\"{\n" +
	"\x17GetWeightStatusResponse\x12\x1b\n" +
	"\tweight_kg\x18\x01 \x01(\x02R\bweightKg\x12\x1f\n" +
	"\vis_overload\x18\x02 \x01(\bR\n" +
	"isOverload\x12\"\n" +
	"\rmax_weight_kg\x18\x03 \x01(\x02R\vmaxWeightKg\"\x18\n" +
	"\x16ReadGroundScaleRequest\"{\n" +
	"\x17ReadGroundScaleResponse\x12\x1b\n" +
	"\tweight_kg\x18\x01 \x01(\x02R\bweightKg\x12\x1f\n" +
	"\vis_overload\x18\x02 \x01(\bR\n" +
	"isOverload\x12\"\n" +
	"\rmax_weight_kg\x18\x03 \x01(\x02R\vmaxWeightKg\"<\n" +
	"\x1dSetGroundScaleOverrideRequest\x12\x1b\n" +
	"\tweight_kg\x18\x01 \x01(\x02R\bweightKg\"T\n" +
	"\x1eSetGroundScaleOverrideResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\x14EmergencyStopRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"K\n" +
	"\x15EmergencyStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\x1aStreamCarrierStatusRequest\x12\x1d\n" +
	"\n" +
	"carrier_id\x18\x01 \x01(\x05R\tcarrierId\"\xb7\x02\n" +
	"\x13CarrierStatusUpdate\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.garage.CarrierStatusR\x06status\x120\n" +
	"\x14ground_carrier_index\x18\x02 \x01(\x05R\x12groundCarrierIndex\x12#\n" +
	"\rcurrent_angle\x18\x03 \x01(\x02R\fcurrentAngle\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x125\n" +
	"\x14target_carrier_index\x18\x05 \x01(\x05H\x00R\x12targetCarrierIndex\x88\x01\x01\x12\x1f\n" +
	"\bprogress\x18\x06 \x01(\x02H\x01R\bprogress\x88\x01\x01B\x17\n" +
	"\x15_target_carrier_indexB\v\n" +
	"\t_progress*7\n" +
	"\x0fRotateDirection\x12\r\n" +
	"\tCLOCKWISE\x10\x00\x12\x15\n" +
	"\x11COUNTER_CLOCKWISE\x10\x01*c\n" +
	"\rCarrierStatus\x12\b\n" +
	"\x04IDLE\x10\x00\x12\f\n" +
	"\bROTATING\x10\x01\x12\x15\n" +
	"\x11EMERGENCY_STOPPED\x10\x02\x12\x13\n" +
	"\x0fWEIGHT_OVERLOAD\x10\x03\x12\x0e\n" +
	"\n" +
	"OBSTRUCTED\x10\x042\xdf\x04\n" +
	"\rGarageService\x12>\n" +
	"\rRotateCarrier\x12\x15.garage.RotateRequest\x1a\x16.garage.RotateResponse\x12U\n" +
	"\x10GetCarrierStatus\x12\x1f.garage.GetCarrierStatusRequest\x1a .garage.GetCarrierStatusResponse\x12R\n" +
	"\x0fGetWeightStatus\x12\x1e.garage.GetWeightStatusRequest\x1a\x1f.garage.GetWeightStatusResponse\x12R\n" +
	"\x0fReadGroundScale\x12\x1e.garage.ReadGroundScaleRequest\x1a\x1f.garage.ReadGroundScaleResponse\x12g\n" +
	"\x16SetGroundScaleOverride\x12%.garage.SetGroundScaleOverrideRequest\x1a&.garage.SetGroundScaleOverrideResponse\x12L\n" +
	"\rEmergencyStop\x12\x1c.garage.EmergencyStopRequest\x1a\x1d.garage.EmergencyStopResponse\x12X\n" +
	"\x13StreamCarrierStatus\x12\".garage.StreamCarrierStatusRequest\x1a\x1b.garage.CarrierStatusUpdate0\x01B3\n" +
	"\x10com.garage.protoB\vGarageProtoP\x01Z\x10gateway-go/protob\x06proto3"

var (
	file_garage_proto_rawDescOnce sync.Once
	file_garage_proto_rawDescData []byte
)

func file_garage_proto_rawDescGZIP() []byte {
	file_garage_proto_rawDescOnce.Do(func() {
		file_garage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garage_proto_rawDesc), len(file_garage_proto_rawDesc)))
	})
	return file_garage_proto_rawDescData
}

var file_garage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_garage_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_garage_proto_goTypes = []any{
	(RotateDirection)(0),                   // 0: garage.RotateDirection
	(CarrierStatus)(0),                     // 1: garage.CarrierStatus
	(*RotateRequest)(nil),                  // 2: garage.RotateRequest
	(*RotateResponse)(nil),                 // 3: garage.RotateResponse
	(*GetCarrierStatusRequest)(nil),        // 4: garage.GetCarrierStatusRequest
	(*GetCarrierStatusResponse)(nil),       // 5: garage.GetCarrierStatusResponse
	(*GetWeightStatusRequest)(nil),         // 6: garage.GetWeightStatusRequest
	(*GetWeightStatusResponse)(nil),        // 7: garage.GetWeightStatusResponse
	(*ReadGroundScaleRequest)(nil),         // 8: garage.ReadGroundScaleRequest
	(*ReadGroundScaleResponse)(nil),        // 9: garage.ReadGroundScaleResponse
	(*SetGroundScaleOverrideRequest)(nil),  // 10: garage.SetGroundScaleOverrideRequest
	(*SetGroundScaleOverrideResponse)(nil), // 11: garage.SetGroundScaleOverrideResponse
	(*EmergencyStopRequest)(nil),           // 12: garage.EmergencyStopRequest
	(*EmergencyStopResponse)(nil),          // 13: garage.EmergencyStopResponse
	(*StreamCarrierStatusRequest)(nil),     // 14: garage.StreamCarrierStatusRequest
	(*CarrierStatusUpdate)(nil),            // 15: garage.CarrierStatusUpdate
}
var file_garage_proto_depIdxs = []int32{
	0,  // 0: garage.RotateRequest.direction:type_name -> garage.RotateDirection
	1,  // 1: garage.GetCarrierStatusResponse.status:type_name -> garage.CarrierStatus
	1,  // 2: garage.CarrierStatusUpdate.status:type_name -> garage.CarrierStatus
	2,  // 3: garage.GarageService.RotateCarrier:input_type -> garage.RotateRequest
	4,  // 4: garage.GarageService.GetCarrierStatus:input_type -> garage.GetCarrierStatusRequest
	6,  // 5: garage.GarageService.GetWeightStatus:input_type -> garage.GetWeightStatusRequest
	8,  // 6: garage.GarageService.ReadGroundScale:input_type -> garage.ReadGroundScaleRequest
	10, // 7: garage.GarageService.SetGroundScaleOverride:input_type -> garage.SetGroundScaleOverrideRequest
	12, // 8: garage.GarageService.EmergencyStop:input_type -> garage.EmergencyStopRequest
	14, // 9: garage.GarageService.StreamCarrierStatus:input_type -> garage.StreamCarrierStatusRequest
	3,  // 10: garage.GarageService.RotateCarrier:output_type -> garage.RotateResponse
	5,  // 11: garage.GarageService.GetCarrierStatus:output_type -> garage.GetCarrierStatusResponse
	7,  // 12: garage.GarageService.GetWeightStatus:output_type -> garage.GetWeightStatusResponse
	9,  // 13: garage.GarageService.ReadGroundScale:output_type -> garage.ReadGroundScaleResponse
	11, // 14: garage.GarageService.SetGroundScaleOverride:output_type -> garage.SetGroundScaleOverrideResponse
	13, // 15: garage.GarageService.EmergencyStop:output_type -> garage.EmergencyStopResponse
	15, // 16: garage.GarageService.StreamCarrierStatus:output_type -> garage.CarrierStatusUpdate
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_garage_proto_init() }
func file_garage_proto_init() {
	if File_garage_proto != nil {
		return
	}
	file_garage_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garage_proto_rawDesc), len(file_garage_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_garage_proto_goTypes,
		DependencyIndexes: file_garage_proto_depIdxs,
		EnumInfos:         file_garage_proto_enumTypes,
		MessageInfos:      file_garage_proto_msgTypes,
	}.Build()
	File_garage_proto = out.File
	file_garage_proto_goTypes = nil
	file_garage_proto_depIdxs = nil
}
